/**
 * The media dispatch engine's public types. Generalized from Open Design's
 * `apps/daemon/src/media/index.ts` `generateMedia` — the real multi-vendor
 * REST dispatch engine, not the substrate (`policy.ts`/`staging.ts`/
 * `task-store.ts`/`video-request.ts`/`capability-registry.ts`) already
 * ported. See `source-map.md` for the full port record: what's ported in
 * this pass vs explicitly deferred.
 *
 * Boundary redesign vs the origin (not a verbatim lift — see source-map.md):
 * the origin resolves an OD `projectId` into a filesystem path and writes
 * generated bytes there directly (`ensureProject`/`sanitizeName`/
 * `mkdir`/write). Jini's kernel has no `Project` concept at all (locked
 * architecture §2.1), so this engine returns bytes to the caller instead —
 * a host pairs this with its own `AttachmentStaging`/`MediaTaskStore`
 * wiring to decide where generated bytes land. Reference-image resolution
 * is the same story: the origin reads a project-relative path itself
 * (`resolveProjectImage`); here the caller resolves any reference image to
 * a data URL before calling, exactly matching the convention `video-
 * request.ts`'s `VideoBuildInput.imageRef` already established for this
 * package — "this package performs no I/O" is a standing invariant across
 * `@jini/media`, not a new one introduced here.
 */
import type { AudioKind, MediaSurface } from '../types.js';

/** Per-provider credentials a host resolves however it wants (env vars, a secrets manager, a config file, ...). This engine never reads `process.env` itself — see `resolveProviderCredentialsFromEnv` in `credentials.ts` for an opt-in reference resolver a host may use to build this map. */
export interface ProviderCredentials {
  readonly apiKey?: string;
  readonly baseUrl?: string;
  readonly model?: string;
}

/** Subset of `RequestInit` a caller may want to control (e.g. a custom `undici.Agent` for connection pooling/timeouts). */
export type MediaGenerationRequestInit = Pick<RequestInit, 'dispatcher'>;

/** A reference image already resolved to a base64 data URL — this package performs no filesystem I/O (see `types.ts`'s `VideoBuildInput.imageRef` for the same convention). */
export interface MediaImageReference {
  readonly dataUrl: string;
}

export type MediaSpeechFormat = 'mp3' | 'wav' | 'flac' | 'aac' | 'opus';

export interface MediaGenerationRequest {
  readonly surface: MediaSurface;
  /** Catalog id (e.g. `dall-e-3`, `gpt-4o-mini-tts`) — must be registered in `@jini/media`'s catalogue for the given surface/audioKind. */
  readonly model: string;
  readonly prompt?: string;
  readonly aspect?: string;
  readonly length?: number;
  readonly duration?: number;
  readonly voice?: string;
  readonly audioKind?: AudioKind;
  readonly language?: string;
  readonly loop?: boolean;
  /**
   * ElevenLabs SFX's "how closely should generation follow the prompt"
   * dial (0-1). Currently unconsumed by any ported renderer — no
   * SFX-capable vendor is wired up in this pass yet — but the field and
   * its validation are real and directly tested via `buildRenderContext`
   * (see `context.ts`), not speculative dead plumbing.
   */
  readonly promptInfluence?: number;
  /** Primary reference image for i2v / image-edit flows. */
  readonly imageRef?: MediaImageReference;
  /**
   * Additional reference images for multi-image i2v / style-reference
   * flows. Currently unconsumed by any ported renderer — no multi-image
   * vendor (e.g. AIHubMix video) is wired up in this pass yet — but, like
   * `promptInfluence`, is directly tested via `buildRenderContext`.
   */
  readonly imageRefs?: readonly MediaImageReference[];
  /**
   * What the provider's request body should carry as `model` (or what gets
   * templated into an Azure-style deployment URL). Defaults to `model`.
   * Capability branches (DALL-E sizing, gpt-image quality, ...) always key
   * off the catalog `model` field, never this one — set this only when a
   * host has its own model-aliasing layer and wants the wire request to
   * carry a different name than the catalog id.
   */
  readonly wireModel?: string;
  /** Desired audio container/codec for speech synthesis. Defaults to `'mp3'`. */
  readonly speechFormat?: MediaSpeechFormat;
  readonly requestInit?: MediaGenerationRequestInit;
  readonly onProgress?: (message: string) => void;
}

export interface MediaGenerationResult {
  readonly bytes: Buffer;
  readonly providerNote: string;
  readonly suggestedExt?: string;
  readonly providerId: string;
  /** `true` when no real renderer was wired up for this (provider, surface) pair and deterministic placeholder bytes were returned instead — see `MediaDispatchEngineOptions.allowStubFallback`. */
  readonly usedStubFallback: boolean;
  /** Non-fatal notices (e.g. a requested `length`/`duration` was clamped to the nearest allowed value). */
  readonly warnings: readonly string[];
}

export interface MediaDispatchEngineOptions {
  /** Per-provider credentials, keyed by provider id (see `providers.ts`'s `MEDIA_PROVIDERS` for valid ids). */
  readonly credentials?: Readonly<Record<string, ProviderCredentials>>;
  /**
   * When a (provider, surface) pair has no real renderer wired up, return
   * deterministic placeholder bytes instead of throwing. Defaults to
   * `false` (fail closed) — matching the origin's own explicitly-gated
   * stub-fallback design (`OD_MEDIA_ALLOW_STUBS`): generated media is
   * costly and a placeholder must never look like a successful real
   * generation by accident, so a host must opt in explicitly rather than
   * getting silent placeholders by default.
   */
  readonly allowStubFallback?: boolean;
}

export interface MediaDispatchEngine {
  generate(request: MediaGenerationRequest): Promise<MediaGenerationResult>;
}

/** Internal: the pure shape rendered by `render*` provider functions, before the engine attaches `providerId`/`usedStubFallback`/`warnings`. */
export interface RenderResult {
  readonly bytes: Buffer;
  readonly providerNote: string;
  readonly suggestedExt?: string;
}

/** Internal: per-generation context threaded into every `render*` provider function. */
export interface RenderContext {
  readonly surface: MediaSurface;
  readonly model: string;
  readonly wireModel: string;
  readonly prompt: string;
  readonly aspect: string | undefined;
  readonly length: number | undefined;
  readonly duration: number | undefined;
  readonly voice: string;
  readonly audioKind: AudioKind | undefined;
  readonly language: string;
  readonly loop: boolean;
  readonly promptInfluence: number | undefined;
  readonly imageRef: MediaImageReference | null;
  readonly imageRefs: readonly MediaImageReference[];
  readonly requestInit: MediaGenerationRequestInit;
  readonly speechFormat: MediaSpeechFormat;
  readonly onProgress?: ((message: string) => void) | undefined;
}
