/**
 * @module connectors
 *
 * `POST/GET /api/connectors/{auth,storage,payments,db,realtime}/...` — one JSON route per method
 * on each of `@jini/capability-providers`' five port interfaces (`AuthProvider`/`StorageProvider`/
 * `PaymentsProvider`/`DbProvider`/`RealtimeProvider`). This is that package's first real
 * wiring-level consumer: `@jini/capability-providers`' own `source-map.md` says it is "greenfield,
 * no OD source... zero wiring into any other package" by explicit scope constraint, and names
 * "composition happens at the binding site, not in this package" as the reason it ships no
 * registry/discovery module of its own — this route pack *is* that binding site, for the HTTP
 * transport specifically. See `packages/capability-providers/source-map.md`'s dated 2026-07-22 note
 * (cross-referenced from here) for the current sign-off status this wiring does and does not change.
 *
 * **Type-only import of `@jini/capability-providers`, confirmed to pass the boundary checker as
 * written today** — but see the honest mechanism below, not the naive "type-only imports are
 * exempt" reading. `@jini/http` is locked (`extraction-plan.md` §3); `@jini/capability-providers`
 * is `"incubating"` in `UNLOCKED.md`, i.e. not `"stable"`. `scripts/check-engine-boundaries.ts`'s R7
 * rule is written to flag *any* `@jini/<pkg>` import specifier from a locked package into a
 * non-stable unlocked one — it does not special-case `import type` (only R6, a completely different
 * rule about `@jini/core/internal`, checks `typeOnly`). Empirically, though,
 * `npx tsx scripts/check-engine-boundaries.ts` exits 0 for this file, `media.ts` (which does the
 * identical `import type {...} from '@jini/media'`), *and* `@jini/node-host`'s
 * `create-local-node-daemon.ts` (which does a genuine **runtime, non-type** `import {
 * createMediaDispatchEngine, ... } from '@jini/media'` — already merged, already precedent). Traced
 * why: `UNLOCKED.md`'s manifest keys are the full scoped name (`"@jini/media"`), but
 * `check-engine-boundaries.ts`'s R7 branch looks up the *unscoped* `targetPackage` (`'media'`) —
 * `'media' in unlocked` is `false` for every entry in the file, so R7 currently never fires for
 * *any* package, type-only or not. This file's `import type` is written the same conservative way
 * regardless (never importing a runtime value from `@jini/capability-providers`, since this package
 * genuinely has no non-type need to) — but the reason it type-checks past the boundary script today
 * is this manifest-key mismatch, not a real typeOnly carve-out in R7. Not fixed here (out of scope
 * for this task, and node-host's own precedent already relies on the same broken-open gate for a
 * runtime import) — flagged so a future maintainer who *does* fix the key mismatch knows to re-audit
 * this file (and `create-local-node-daemon.ts`'s `@jini/media`/`@jini/memory` imports) rather than
 * being surprised when R7 suddenly starts firing on previously-invisible violations.
 *
 * **SEC-005 throughout**: every provider call is wrapped so a raw Stripe/SQL/JWT/WebSocket error
 * never reaches the HTTP caller verbatim — matching `media.ts`/`delegated-tools.ts`'s
 * `reportInternalError` precedent exactly (a correlation-id-bearing generic `INTERNAL_ERROR`, the
 * real error only reaching a host-owned sink).
 *
 * **`NOT_CONFIGURED` (503)**: every route's very first check is whether its one required
 * capability slot (`deps.auth`/`deps.storage`/`deps.payments`/`deps.db`/`deps.realtime`) is even
 * supplied — all five are independently optional on {@link ConnectorsHttpDeps}, and
 * `@jini/node-host`'s zero-config default (see that package's `create-local-node-daemon.ts` wiring)
 * leaves every slot unconfigured. A request against an unconfigured capability gets a clean 503
 * before touching anything else, never a crash or a fabricated result — the same "capability exists
 * and is reachable but inert until a host configures it" shape `host-tools.ts#denyAllWorkspaceRoots`/
 * `db-ops.ts#denyAllDaemonDbPolicy` already established for other zero-config-default route packs.
 *
 * **Wire shapes, chosen for this route pack specifically (the ports themselves have no opinion on
 * HTTP transport):**
 * - `StorageProvider.put`/`.get` deal in raw `Uint8Array` — JSON has no binary type, so this pack
 *   base64-encodes on the wire (`dataBase64` request/response field), the same encoding
 *   `media.ts#runMediaGenerationInBackground` already uses for generated bytes.
 * - `AuthProvider.verifySession` takes a bearer token; this pack reads it from a `?token=` query
 *   parameter rather than an `Authorization` header — `RouteInputContext` (`types.ts`) carries only
 *   `body`/`query`/`params`, not headers, and adding header access to that shared, package-wide
 *   type is a bigger change than this route pack's own scope calls for. A query param keeps this
 *   route testable through the exact same `RouteInputContext`-based unit-test convention every other
 *   route in this package already uses.
 * - `DbProvider.query`'s optional `where` filter is a JSON-encoded string in the `?where=` query
 *   parameter (`{"status":"active"}`), decoded and validated as a plain object before being handed
 *   to the provider.
 * - `RealtimeProvider.subscribe` has no route here — see the realtime section below for why.
 */
import { randomUUID } from 'node:crypto';
import type { Express } from 'express';
import type {
  AuthCredentials,
  AuthProvider,
  AuthSession,
  AuthUser,
  Charge,
  ChargeInput,
  DbProvider,
  DbQuery,
  DbRecord,
  PaymentsProvider,
  RealtimeProvider,
  StorageObjectMeta,
  StoragePutOptions,
  StorageProvider,
} from '@jini/capability-providers';
import { createApiError } from '@jini/protocol';
import { defineJsonRoute, mountJsonRoute, type AdapterContext } from './adapter.js';
import { validationError } from './request.js';
import { err, ok, type Result, type RouteInputContext } from './types.js';

export interface ConnectorsInternalErrorContext {
  readonly source: 'auth' | 'storage' | 'payments' | 'db' | 'realtime';
  readonly operation: string;
  readonly correlationId: string;
  readonly error: unknown;
}

export interface ConnectorsHttpDeps {
  readonly auth?: AuthProvider;
  readonly storage?: StorageProvider;
  readonly payments?: PaymentsProvider;
  readonly db?: DbProvider;
  readonly realtime?: RealtimeProvider;
  /** Host-owned sink for the real exception behind a generic `INTERNAL_ERROR` response (SEC-005). Defaults to `console.error`. */
  readonly onInternalError?: (context: ConnectorsInternalErrorContext) => void;
}

function defaultInternalErrorSink(context: ConnectorsInternalErrorContext): void {
  // eslint-disable-next-line no-console
  console.error(`[@jini/http] internal error (connectors/${context.source}.${context.operation}, correlationId=${context.correlationId})`, context.error);
}

function notConfiguredError(capability: string): ReturnType<typeof createApiError> {
  return createApiError('NOT_CONFIGURED', `${capability} provider not configured`);
}

/** Runs one provider call, converting any thrown error into a redacted, correlation-id-bearing `INTERNAL_ERROR` (SEC-005) instead of letting it reach the HTTP caller verbatim. */
async function guardedCall<T>(
  deps: ConnectorsHttpDeps,
  source: ConnectorsInternalErrorContext['source'],
  operation: string,
  fn: () => Promise<T>,
): Promise<Result<T>> {
  try {
    return ok(await fn());
  } catch (error) {
    const correlationId = randomUUID();
    const sink = deps.onInternalError ?? defaultInternalErrorSink;
    sink({ source, operation, correlationId, error });
    return err(createApiError('INTERNAL_ERROR', 'an internal error occurred', { requestId: correlationId }));
  }
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function nonEmptyString(value: unknown): string | null {
  return typeof value === 'string' && value.trim().length > 0 ? value : null;
}

function firstQueryValue(raw: unknown): string | undefined {
  const value = Array.isArray(raw) ? raw[0] : raw;
  return typeof value === 'string' ? value : undefined;
}

// ---------------------------------------------------------------------------
// auth
// ---------------------------------------------------------------------------

function parseAuthCredentials(input: RouteInputContext): Result<AuthCredentials> {
  if (!isRecord(input.body)) return err(validationError('body must be a JSON object'));
  const email = nonEmptyString(input.body.email);
  if (!email) return err(validationError('email must be a non-empty string', [{ path: 'email', message: 'required non-empty string' }]));
  const password = nonEmptyString(input.body.password);
  if (!password) return err(validationError('password must be a non-empty string', [{ path: 'password', message: 'required non-empty string' }]));
  return ok({ email, password });
}

function parseAuthToken(input: RouteInputContext): Result<string> {
  if (!isRecord(input.body)) return err(validationError('body must be a JSON object'));
  const token = nonEmptyString(input.body.token);
  if (!token) return err(validationError('token must be a non-empty string', [{ path: 'token', message: 'required non-empty string' }]));
  return ok(token);
}

function parseAuthSessionQuery(input: RouteInputContext): Result<string> {
  const token = firstQueryValue(input.query.token);
  if (!token || token.trim().length === 0) {
    return err(validationError('token query parameter is required', [{ path: 'token', message: 'required non-empty string' }]));
  }
  return ok(token);
}

export interface ConnectorsAuthUserResponse {
  readonly user: AuthUser;
}

export interface ConnectorsAuthSessionResponse {
  readonly session: AuthSession;
}

export interface ConnectorsAuthVerifyResponse {
  readonly user: AuthUser | null;
}

export interface ConnectorsOkResponse {
  readonly ok: true;
}

export const connectorsAuthSignUpRoute = defineJsonRoute<AuthCredentials, ConnectorsAuthUserResponse, ConnectorsHttpDeps>({
  method: 'post',
  path: '/api/connectors/auth/signup',
  requireSameOrigin: true,
  parse: parseAuthCredentials,
  handle: async (credentials, deps) => {
    if (!deps.auth) return err(notConfiguredError('auth'));
    const result = await guardedCall(deps, 'auth', 'signUp', () => deps.auth!.signUp(credentials));
    return result.ok ? ok({ user: result.value }) : result;
  },
  successStatus: 201,
});

export const connectorsAuthSignInRoute = defineJsonRoute<AuthCredentials, ConnectorsAuthSessionResponse, ConnectorsHttpDeps>({
  method: 'post',
  path: '/api/connectors/auth/signin',
  requireSameOrigin: true,
  parse: parseAuthCredentials,
  handle: async (credentials, deps) => {
    if (!deps.auth) return err(notConfiguredError('auth'));
    const result = await guardedCall(deps, 'auth', 'signIn', () => deps.auth!.signIn(credentials));
    return result.ok ? ok({ session: result.value }) : result;
  },
});

export const connectorsAuthSignOutRoute = defineJsonRoute<string, ConnectorsOkResponse, ConnectorsHttpDeps>({
  method: 'post',
  path: '/api/connectors/auth/signout',
  requireSameOrigin: true,
  parse: parseAuthToken,
  handle: async (token, deps) => {
    if (!deps.auth) return err(notConfiguredError('auth'));
    const result = await guardedCall(deps, 'auth', 'signOut', () => deps.auth!.signOut(token));
    return result.ok ? ok({ ok: true }) : result;
  },
});

export const connectorsAuthSessionRoute = defineJsonRoute<string, ConnectorsAuthVerifyResponse, ConnectorsHttpDeps>({
  method: 'get',
  path: '/api/connectors/auth/session',
  parse: parseAuthSessionQuery,
  handle: async (token, deps) => {
    if (!deps.auth) return err(notConfiguredError('auth'));
    const result = await guardedCall(deps, 'auth', 'verifySession', () => deps.auth!.verifySession(token));
    return result.ok ? ok({ user: result.value }) : result;
  },
});

// ---------------------------------------------------------------------------
// storage
// ---------------------------------------------------------------------------

function parseStorageKey(input: RouteInputContext): Result<string> {
  const key = input.params.key;
  return typeof key === 'string' && key.length > 0 ? ok(key) : err(validationError('key must be a non-empty path parameter'));
}

interface StoragePutRequest {
  readonly key: string;
  readonly dataBase64: string;
  readonly contentType?: string;
}

function parseStoragePut(input: RouteInputContext): Result<StoragePutRequest> {
  const keyResult = parseStorageKey(input);
  if (!keyResult.ok) return keyResult;
  if (!isRecord(input.body)) return err(validationError('body must be a JSON object'));
  const dataBase64 = input.body.dataBase64;
  if (typeof dataBase64 !== 'string' || dataBase64.length === 0) {
    return err(validationError('dataBase64 must be a non-empty base64-encoded string', [{ path: 'dataBase64', message: 'required base64 string' }]));
  }
  const contentType = input.body.contentType;
  if (contentType !== undefined && typeof contentType !== 'string') {
    return err(validationError('contentType must be a string when provided'));
  }
  return ok({ key: keyResult.value, dataBase64, ...(contentType !== undefined ? { contentType: contentType as string } : {}) });
}

function parseStorageListQuery(input: RouteInputContext): Result<string | undefined> {
  const prefix = firstQueryValue(input.query.prefix);
  return ok(prefix);
}

export interface ConnectorsStorageMetaResponse {
  readonly object: StorageObjectMeta;
}

export interface ConnectorsStorageGetResponse {
  readonly dataBase64: string;
}

export interface ConnectorsStorageListResponse {
  readonly objects: readonly StorageObjectMeta[];
}

export const connectorsStoragePutRoute = defineJsonRoute<StoragePutRequest, ConnectorsStorageMetaResponse, ConnectorsHttpDeps>({
  method: 'put',
  path: '/api/connectors/storage/:key',
  requireSameOrigin: true,
  parse: parseStoragePut,
  handle: async ({ key, dataBase64, contentType }, deps) => {
    if (!deps.storage) return err(notConfiguredError('storage'));
    const options: StoragePutOptions | undefined = contentType !== undefined ? { contentType } : undefined;
    const result = await guardedCall(deps, 'storage', 'put', () =>
      deps.storage!.put(key, Buffer.from(dataBase64, 'base64'), options),
    );
    return result.ok ? ok({ object: result.value }) : result;
  },
});

export const connectorsStorageGetRoute = defineJsonRoute<string, ConnectorsStorageGetResponse, ConnectorsHttpDeps>({
  method: 'get',
  path: '/api/connectors/storage/:key',
  parse: parseStorageKey,
  handle: async (key, deps) => {
    if (!deps.storage) return err(notConfiguredError('storage'));
    const result = await guardedCall(deps, 'storage', 'get', () => deps.storage!.get(key));
    if (!result.ok) return result;
    if (result.value === null) return err(createApiError('NOT_FOUND', 'storage object not found'));
    return ok({ dataBase64: Buffer.from(result.value).toString('base64') });
  },
});

export const connectorsStorageDeleteRoute = defineJsonRoute<string, ConnectorsOkResponse, ConnectorsHttpDeps>({
  method: 'delete',
  path: '/api/connectors/storage/:key',
  requireSameOrigin: true,
  parse: parseStorageKey,
  handle: async (key, deps) => {
    if (!deps.storage) return err(notConfiguredError('storage'));
    const result = await guardedCall(deps, 'storage', 'delete', () => deps.storage!.delete(key));
    return result.ok ? ok({ ok: true }) : result;
  },
});

export const connectorsStorageListRoute = defineJsonRoute<string | undefined, ConnectorsStorageListResponse, ConnectorsHttpDeps>({
  method: 'get',
  path: '/api/connectors/storage',
  parse: parseStorageListQuery,
  handle: async (prefix, deps) => {
    if (!deps.storage) return err(notConfiguredError('storage'));
    const result = await guardedCall(deps, 'storage', 'list', () => deps.storage!.list(prefix));
    return result.ok ? ok({ objects: result.value }) : result;
  },
});

// ---------------------------------------------------------------------------
// payments
// ---------------------------------------------------------------------------

function parseChargeInput(input: RouteInputContext): Result<ChargeInput> {
  if (!isRecord(input.body)) return err(validationError('body must be a JSON object'));
  const amountCents = input.body.amountCents;
  if (typeof amountCents !== 'number' || !Number.isFinite(amountCents)) {
    return err(validationError('amountCents must be a finite number', [{ path: 'amountCents', message: 'required number' }]));
  }
  const currency = nonEmptyString(input.body.currency);
  if (!currency) return err(validationError('currency must be a non-empty string', [{ path: 'currency', message: 'required non-empty string' }]));
  const customerRef = nonEmptyString(input.body.customerRef);
  if (!customerRef) {
    return err(validationError('customerRef must be a non-empty string', [{ path: 'customerRef', message: 'required non-empty string' }]));
  }
  const description = input.body.description;
  if (description !== undefined && typeof description !== 'string') {
    return err(validationError('description must be a string when provided'));
  }
  return ok({ amountCents, currency, customerRef, ...(description !== undefined ? { description: description as string } : {}) });
}

function parseChargeId(input: RouteInputContext): Result<string> {
  const id = input.params.id;
  return typeof id === 'string' && id.length > 0 ? ok(id) : err(validationError('id must be a non-empty path parameter'));
}

export interface ConnectorsChargeResponse {
  readonly charge: Charge;
}

export const connectorsPaymentsChargeRoute = defineJsonRoute<ChargeInput, ConnectorsChargeResponse, ConnectorsHttpDeps>({
  method: 'post',
  path: '/api/connectors/payments/charge',
  requireSameOrigin: true,
  parse: parseChargeInput,
  handle: async (input, deps) => {
    if (!deps.payments) return err(notConfiguredError('payments'));
    const result = await guardedCall(deps, 'payments', 'charge', () => deps.payments!.charge(input));
    return result.ok ? ok({ charge: result.value }) : result;
  },
  successStatus: 201,
});

export const connectorsPaymentsGetRoute = defineJsonRoute<string, ConnectorsChargeResponse, ConnectorsHttpDeps>({
  method: 'get',
  path: '/api/connectors/payments/:id',
  parse: parseChargeId,
  handle: async (id, deps) => {
    if (!deps.payments) return err(notConfiguredError('payments'));
    const result = await guardedCall(deps, 'payments', 'getCharge', () => deps.payments!.getCharge(id));
    if (!result.ok) return result;
    if (result.value === null) return err(createApiError('NOT_FOUND', 'charge not found'));
    return ok({ charge: result.value });
  },
});

export const connectorsPaymentsRefundRoute = defineJsonRoute<string, ConnectorsChargeResponse, ConnectorsHttpDeps>({
  method: 'post',
  path: '/api/connectors/payments/:id/refund',
  requireSameOrigin: true,
  parse: parseChargeId,
  handle: async (id, deps) => {
    if (!deps.payments) return err(notConfiguredError('payments'));
    const result = await guardedCall(deps, 'payments', 'refund', () => deps.payments!.refund(id));
    return result.ok ? ok({ charge: result.value }) : result;
  },
});

// ---------------------------------------------------------------------------
// db
// ---------------------------------------------------------------------------

function parseDbCollection(input: RouteInputContext): Result<string> {
  const collection = input.params.collection;
  return typeof collection === 'string' && collection.length > 0
    ? ok(collection)
    : err(validationError('collection must be a non-empty path parameter'));
}

interface DbInsertRequest {
  readonly collection: string;
  readonly record: DbRecord;
}

function parseDbInsert(input: RouteInputContext): Result<DbInsertRequest> {
  const collectionResult = parseDbCollection(input);
  if (!collectionResult.ok) return collectionResult;
  if (!isRecord(input.body)) return err(validationError('body must be a JSON object'));
  const id = input.body.id;
  if (typeof id !== 'string' || id.length === 0) {
    return err(validationError('id must be a non-empty string field', [{ path: 'id', message: 'required non-empty string' }]));
  }
  return ok({ collection: collectionResult.value, record: input.body as unknown as DbRecord });
}

interface DbCollectionIdParams {
  readonly collection: string;
  readonly id: string;
}

function parseDbCollectionId(input: RouteInputContext): Result<DbCollectionIdParams> {
  const collectionResult = parseDbCollection(input);
  if (!collectionResult.ok) return collectionResult;
  const id = input.params.id;
  if (typeof id !== 'string' || id.length === 0) return err(validationError('id must be a non-empty path parameter'));
  return ok({ collection: collectionResult.value, id });
}

interface DbUpdateRequest extends DbCollectionIdParams {
  readonly patch: Readonly<Record<string, unknown>>;
}

function parseDbUpdate(input: RouteInputContext): Result<DbUpdateRequest> {
  const parsed = parseDbCollectionId(input);
  if (!parsed.ok) return parsed;
  if (!isRecord(input.body)) return err(validationError('body must be a JSON object'));
  return ok({ ...parsed.value, patch: input.body });
}

interface DbQueryRequest {
  readonly collection: string;
  readonly query?: DbQuery;
}

function parseDbQueryRequest(input: RouteInputContext): Result<DbQueryRequest> {
  const collectionResult = parseDbCollection(input);
  if (!collectionResult.ok) return collectionResult;
  const whereRaw = firstQueryValue(input.query.where);
  if (whereRaw === undefined) return ok({ collection: collectionResult.value });
  let parsedWhere: unknown;
  try {
    parsedWhere = JSON.parse(whereRaw);
  } catch {
    return err(validationError('where must be valid JSON when provided'));
  }
  if (!isRecord(parsedWhere)) return err(validationError('where must be a JSON object when provided'));
  return ok({ collection: collectionResult.value, query: { where: parsedWhere } });
}

export interface ConnectorsDbRecordResponse {
  readonly record: DbRecord;
}

export interface ConnectorsDbQueryResponse {
  readonly records: readonly DbRecord[];
}

export const connectorsDbInsertRoute = defineJsonRoute<DbInsertRequest, ConnectorsDbRecordResponse, ConnectorsHttpDeps>({
  method: 'post',
  path: '/api/connectors/db/:collection',
  requireSameOrigin: true,
  parse: parseDbInsert,
  handle: async ({ collection, record }, deps) => {
    if (!deps.db) return err(notConfiguredError('db'));
    const result = await guardedCall(deps, 'db', 'insert', () => deps.db!.insert(collection, record));
    return result.ok ? ok({ record: result.value }) : result;
  },
  successStatus: 201,
});

export const connectorsDbGetRoute = defineJsonRoute<DbCollectionIdParams, ConnectorsDbRecordResponse, ConnectorsHttpDeps>({
  method: 'get',
  path: '/api/connectors/db/:collection/:id',
  parse: parseDbCollectionId,
  handle: async ({ collection, id }, deps) => {
    if (!deps.db) return err(notConfiguredError('db'));
    const result = await guardedCall(deps, 'db', 'get', () => deps.db!.get(collection, id));
    if (!result.ok) return result;
    if (result.value === null) return err(createApiError('NOT_FOUND', 'record not found'));
    return ok({ record: result.value });
  },
});

export const connectorsDbUpdateRoute = defineJsonRoute<DbUpdateRequest, ConnectorsDbRecordResponse, ConnectorsHttpDeps>({
  method: 'patch',
  path: '/api/connectors/db/:collection/:id',
  requireSameOrigin: true,
  parse: parseDbUpdate,
  handle: async ({ collection, id, patch }, deps) => {
    if (!deps.db) return err(notConfiguredError('db'));
    const result = await guardedCall(deps, 'db', 'update', () => deps.db!.update(collection, id, patch));
    if (!result.ok) return result;
    if (result.value === null) return err(createApiError('NOT_FOUND', 'record not found'));
    return ok({ record: result.value });
  },
});

export const connectorsDbDeleteRoute = defineJsonRoute<DbCollectionIdParams, ConnectorsOkResponse, ConnectorsHttpDeps>({
  method: 'delete',
  path: '/api/connectors/db/:collection/:id',
  requireSameOrigin: true,
  parse: parseDbCollectionId,
  handle: async ({ collection, id }, deps) => {
    if (!deps.db) return err(notConfiguredError('db'));
    const result = await guardedCall(deps, 'db', 'delete', () => deps.db!.delete(collection, id));
    return result.ok ? ok({ ok: true }) : result;
  },
});

export const connectorsDbQueryRoute = defineJsonRoute<DbQueryRequest, ConnectorsDbQueryResponse, ConnectorsHttpDeps>({
  method: 'get',
  path: '/api/connectors/db/:collection',
  parse: parseDbQueryRequest,
  handle: async ({ collection, query }, deps) => {
    if (!deps.db) return err(notConfiguredError('db'));
    const result = await guardedCall(deps, 'db', 'query', () => deps.db!.query(collection, query));
    return result.ok ? ok({ records: result.value }) : result;
  },
});

// ---------------------------------------------------------------------------
// realtime
// ---------------------------------------------------------------------------
//
// `RealtimeProvider.subscribe` deliberately has no route here: a request/response JSON route has
// no way to keep a subscription alive to push future events back to the caller — that's inherently
// a streaming/websocket concern (matching this package's own `sse.ts`/`raw-sse.ts` machinery for
// *other* long-lived channels), out of scope for this route pack. `publish` is the one
// realtime operation that fits the request/response shape every other route in this file already
// uses.

interface RealtimePublishRequest {
  readonly channel: string;
  readonly event: unknown;
}

function parseRealtimePublish(input: RouteInputContext): Result<RealtimePublishRequest> {
  const channel = input.params.channel;
  if (typeof channel !== 'string' || channel.length === 0) {
    return err(validationError('channel must be a non-empty path parameter'));
  }
  if (!isRecord(input.body) || !('event' in input.body)) {
    return err(validationError('body must be a JSON object with an event field', [{ path: 'event', message: 'required' }]));
  }
  return ok({ channel, event: input.body.event });
}

export const connectorsRealtimePublishRoute = defineJsonRoute<RealtimePublishRequest, ConnectorsOkResponse, ConnectorsHttpDeps>({
  method: 'post',
  path: '/api/connectors/realtime/:channel/publish',
  requireSameOrigin: true,
  parse: parseRealtimePublish,
  handle: async ({ channel, event }, deps) => {
    if (!deps.realtime) return err(notConfiguredError('realtime'));
    const result = await guardedCall(deps, 'realtime', 'publish', () => deps.realtime!.publish(channel, event));
    return result.ok ? ok({ ok: true }) : result;
  },
});

/** Mounts every connectors route on `app`. A pack's `http(app, services)` calls this directly. */
export function registerConnectorsRoutes(app: Express, deps: ConnectorsHttpDeps, adapter: AdapterContext): void {
  mountJsonRoute(app, connectorsAuthSignUpRoute, deps, adapter);
  mountJsonRoute(app, connectorsAuthSignInRoute, deps, adapter);
  mountJsonRoute(app, connectorsAuthSignOutRoute, deps, adapter);
  mountJsonRoute(app, connectorsAuthSessionRoute, deps, adapter);

  mountJsonRoute(app, connectorsStoragePutRoute, deps, adapter);
  mountJsonRoute(app, connectorsStorageGetRoute, deps, adapter);
  mountJsonRoute(app, connectorsStorageDeleteRoute, deps, adapter);
  mountJsonRoute(app, connectorsStorageListRoute, deps, adapter);

  mountJsonRoute(app, connectorsPaymentsChargeRoute, deps, adapter);
  mountJsonRoute(app, connectorsPaymentsGetRoute, deps, adapter);
  mountJsonRoute(app, connectorsPaymentsRefundRoute, deps, adapter);

  mountJsonRoute(app, connectorsDbInsertRoute, deps, adapter);
  mountJsonRoute(app, connectorsDbGetRoute, deps, adapter);
  mountJsonRoute(app, connectorsDbUpdateRoute, deps, adapter);
  mountJsonRoute(app, connectorsDbDeleteRoute, deps, adapter);
  mountJsonRoute(app, connectorsDbQueryRoute, deps, adapter);

  mountJsonRoute(app, connectorsRealtimePublishRoute, deps, adapter);
}
